// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'fm_bar_element.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FMBarElement>>
abstract class FmBarElement implements RustOpaqueInterface {}

@freezed
sealed class BarBeatData with _$BarBeatData {
  const BarBeatData._();

  const factory BarBeatData.int(
    Int32List field0,
  ) = BarBeatData_Int;
  const factory BarBeatData.float(
    Float32List field0,
  ) = BarBeatData_Float;
}

class FMBarElement {
  final int nom;
  final int denom;
  final double nomSecs;
  final BarBeatData beats;
  final bool hasSignature;
  final BarBeatData subBeats;

  const FMBarElement({
    required this.nom,
    required this.denom,
    required this.nomSecs,
    required this.beats,
    required this.hasSignature,
    required this.subBeats,
  });

  Future<void> addSubBeat({required double value}) => RustLib.instance.api
      .crateApiFmBarElementFmBarElementAddSubBeat(that: this, value: value);

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<FMBarElement> newInstance(
          {required int nom,
          required int denom,
          required double nomSecs,
          Int32List? beats}) =>
      RustLib.instance.api.crateApiFmBarElementFmBarElementNew(
          nom: nom, denom: denom, nomSecs: nomSecs, beats: beats);

  @override
  int get hashCode =>
      nom.hashCode ^
      denom.hashCode ^
      nomSecs.hashCode ^
      beats.hashCode ^
      hasSignature.hashCode ^
      subBeats.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FMBarElement &&
          runtimeType == other.runtimeType &&
          nom == other.nom &&
          denom == other.denom &&
          nomSecs == other.nomSecs &&
          beats == other.beats &&
          hasSignature == other.hasSignature &&
          subBeats == other.subBeats;
}
