// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'fm_ticker_base.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'fm_base.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `linspace`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`, `from`, `from`, `hash`

/// Load beat configuration from YAML file
Future<Map<MetricKey, Int32List>> loadBeatConfig() =>
    RustLib.instance.api.crateApiFmBaseLoadBeatConfig();

@freezed
sealed class MetricKey with _$MetricKey {
  const MetricKey._();

  const factory MetricKey.standard(
    (int, int) field0,
  ) = MetricKey_Standard;
  const factory MetricKey.composite(
    (Int32List, int) field0,
  ) = MetricKey_Composite;
}
