// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'fm_bar_element.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `calculate_bar_duration_ms`, `calculate_beat_events`, `calculate_note_duration_with_tempo_change`, `calculate_section_duration_with_tempo_change`, `calculate_total_beat_units`, `calculate_total_quarter_notes`, `convert_tempo_to_bpm`, `extract_beats`, `extract_subbeats`, `trigger_callback`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `hash`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `new_internal`, `new`, `set_tick_callback`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BeatEvent>>
abstract class BeatEvent implements RustOpaqueInterface {
  BigInt get barIndex;

  BigInt get beatInBar;

  BeatType get beatType;

  int get denom;

  int get nom;

  BigInt get subbeatInBeat;

  double get tempoBpm;

  double get timeOffsetMs;

  set barIndex(BigInt barIndex);

  set beatInBar(BigInt beatInBar);

  set beatType(BeatType beatType);

  set denom(int denom);

  set nom(int nom);

  set subbeatInBeat(BigInt subbeatInBeat);

  set tempoBpm(double tempoBpm);

  set timeOffsetMs(double timeOffsetMs);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Box < Error >>>
abstract class BoxError implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Duration>>
abstract class Duration implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FMCircleTicker>>
abstract class FmCircleTicker implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FMSectionTimer>>
abstract class FmSectionTimer implements RustOpaqueInterface, AsyncTimer {
  Future<List<String>?> getBeatEventsDebug();

  /// Get the total duration of the musical section in milliseconds
  Future<double> getTotalDurationMs();

  @override
  Future<bool> isRunning();

  Future<void> manualTick(
      {required FMBarElement sectionInfo,
      required int cnt,
      bool? ignoreSubbeats,
      required BeatType beatType});

  /// FRB-compatible constructor that accepts TimeDelta and converts to Duration
  factory FmSectionTimer({required TimeDelta intervalDuration}) =>
      RustLib.instance.api.crateApiFmTickerBaseFmSectionTimerNew(
          intervalDuration: intervalDuration);

  /// Create a timer for a musical section with bars and tempo changes
  /// start_tempo_bpm and end_tempo_bpm should be in quarter notes per minute
  static Future<FmSectionTimer> newWithSection(
          {required List<FMBarElement> sectionBars,
          required double startTempoBpm,
          required double endTempoBpm}) =>
      RustLib.instance.api.crateApiFmTickerBaseFmSectionTimerNewWithSection(
          sectionBars: sectionBars,
          startTempoBpm: startTempoBpm,
          endTempoBpm: endTempoBpm);

  @override
  Future<void> setInterval({required Duration duration});

  /// Set interval using TimeDelta - FRB-compatible version
  void setIntervalDuration({required TimeDelta duration});

  @override
  Future<void> start();

  @override
  Future<void> stop();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FlutterTicker>>
abstract class FlutterTicker implements RustOpaqueInterface, FMTickerBase {
  Future<void> createSection(
      {required List<FMBarElement> sectionBars,
      required double startTempoBpm,
      required double endTempoBpm});

  static Future<int> fixSubbeat(
          {required int tickValue, bool? ignoreSubbeats}) =>
      RustLib.instance.api.crateApiFmTickerBaseFlutterTickerFixSubbeat(
          tickValue: tickValue, ignoreSubbeats: ignoreSubbeats);

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<FlutterTicker> newInstance() =>
      RustLib.instance.api.crateApiFmTickerBaseFlutterTickerNew();

  Future<void> start();

  Future<void> stop();

  @override
  Future<void> tickCallback(
      {required FMBarElement sectionInfo,
      required int cnt,
      bool? ignoreSubbeats,
      required BeatType beatType});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TimeDelta>>
abstract class TimeDelta implements RustOpaqueInterface {}

abstract class AsyncTimer {
  Future<bool> isRunning();

  Future<void> setInterval({required Duration duration});

  Future<void> start();

  Future<void> stop();
}

abstract class FMTickerBase {
  Future<void> tickCallback(
      {required FMBarElement sectionInfo,
      required int cnt,
      bool? ignoreSubbeats,
      required BeatType beatType});
}

/// Beat type classification for musical timing
enum BeatType {
  major,
  medium,
  minor,
  ;
}

class FMCircleTicker {
  final FmSectionTimer? timer;
  final FMTickPositions state;
  final FMTickPositions tickPositions;

  const FMCircleTicker({
    this.timer,
    required this.state,
    required this.tickPositions,
  });

  Future<void> connectTimer({required FmSectionTimer timer}) => RustLib
      .instance.api
      .crateApiFmTickerBaseFmCircleTickerConnectTimer(that: this, timer: timer);

  static Future<int> fixSubbeat(
          {required int tickValue, bool? ignoreSubbeats}) =>
      RustLib.instance.api.crateApiFmTickerBaseFmCircleTickerFixSubbeat(
          tickValue: tickValue, ignoreSubbeats: ignoreSubbeats);

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<FMCircleTicker> newInstance() =>
      RustLib.instance.api.crateApiFmTickerBaseFmCircleTickerNew();

  Future<void> startTimer() =>
      RustLib.instance.api.crateApiFmTickerBaseFmCircleTickerStartTimer(
        that: this,
      );

  Future<void> stopTimer() =>
      RustLib.instance.api.crateApiFmTickerBaseFmCircleTickerStopTimer(
        that: this,
      );

  Future<void> tickCallback(
          {required FMBarElement sectionInfo,
          required int cnt,
          bool? ignoreSubbeats,
          required BeatType beatType}) =>
      RustLib.instance.api.crateApiFmTickerBaseFmCircleTickerTickCallback(
          that: this,
          sectionInfo: sectionInfo,
          cnt: cnt,
          ignoreSubbeats: ignoreSubbeats,
          beatType: beatType);

  @override
  int get hashCode => timer.hashCode ^ state.hashCode ^ tickPositions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FMCircleTicker &&
          runtimeType == other.runtimeType &&
          timer == other.timer &&
          state == other.state &&
          tickPositions == other.tickPositions;
}

enum FMTickPositions {
  tNone,
  tSection,
  tRest,
  tMedium,
  tMinor,
  ;
}

/// Musical timing helper that calculates tempo changes and beat intervals
/// within a section of bars with potentially changing time signatures and tempos
class MusicalTiming {
  final List<BeatEvent> beatEvents;
  final double totalDurationMs;
  final double startTempoBpm;
  final double endTempoBpm;

  const MusicalTiming({
    required this.beatEvents,
    required this.totalDurationMs,
    required this.startTempoBpm,
    required this.endTempoBpm,
  });

  /// Get all beat events for iteration
  Future<void> getBeatEvents() =>
      RustLib.instance.api.crateApiFmTickerBaseMusicalTimingGetBeatEvents(
        that: this,
      );

  /// Get the next beat event at or after the given time
  Future<BeatEvent?> getNextBeatEvent({required double currentTimeMs}) =>
      RustLib.instance.api.crateApiFmTickerBaseMusicalTimingGetNextBeatEvent(
          that: this, currentTimeMs: currentTimeMs);

  /// Get the total duration of the musical section in milliseconds
  Future<double> getTotalDurationMs() =>
      RustLib.instance.api.crateApiFmTickerBaseMusicalTimingGetTotalDurationMs(
        that: this,
      );

  @override
  int get hashCode =>
      beatEvents.hashCode ^
      totalDurationMs.hashCode ^
      startTempoBpm.hashCode ^
      endTempoBpm.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MusicalTiming &&
          runtimeType == other.runtimeType &&
          beatEvents == other.beatEvents &&
          totalDurationMs == other.totalDurationMs &&
          startTempoBpm == other.startTempoBpm &&
          endTempoBpm == other.endTempoBpm;
}
